### ISSUE TITLE
Increase Dropbox app user limit

### ISSUE THREAD

**Issue by everytowndev** [donpiekarz/spellbook#6]
I am trying to connect spellbook to Dropbox by using:     `spellbook - connectdb`    and then going to: 

https://www.dropbox.com/1/oauth2/authorize?response_type=code&client_id=ow3gosk8pb9bhkr

But, it gives the following error message:

> This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

Could you please raise the dropbox app's user limit?

**Comment by donpiekarz** [comment]
oh, I forgot :)

Now it's fixed, 99 users can use dropbox. 

I will apply for more :)

**Comment by everytowndev** [comment]
Thanks, that worked. :+1:
